### ISSUE TITLE
route ip+net: no such network interface

### ISSUE THREAD

**Issue by adagari** [pyther/openwrt-feed#1]
I have been using the python version of this package and saw you have updated it to golang. I went ahead and included it in my firmware as I was upgrading to 19.07.3. I have it running on a WRT3200ACM.

The package does seem to be working but I do receive an error while booting. 
`kern.info goeap_proxy[2166]: interface by name eth1.2: route ip+net: no such network interface `

The package goes on to recover and proxies the packets as expected. I'm not sure of the root cause but a few more lines down in the log it says 
`daemon.notice netifd: VLAN 'eth1.2' link is up `

I suspect it may be called before the interface is ready. Error checking seems to start on line 68 in main.go but I haven't tested to see if the service file is the main culprit.

**Comment by pyther** [comment]
Thanks for the report. Any chance you could provide the full log output of goeap_proxy? I suspect we crashed and then procd respawned the instance. I'll try to figure out the best way to handle this. Would you mind submitting an issue against [goeap_proxy](https://github.com/pyther/goeap_proxy/issues)

**Comment by pyther** [comment]
Thanks for the report. The error message could certainly be a bit more clear. 

Your analysis of the situation is correct. goeap_proxy tried to lookup `eth1.2`, failed, and exited. The init script has respawn logic
```
procd_set_param respawn ${respawn_threshold:-2} ${respawn_timeout:-30} ${respawn_retry:-0}
```
This will respawn goeap_proxy every 30 seconds.

**Comment by pyther** [comment]
What is the reason for using `eth1.2`? Unless you have a weird networking setup, it shouldn't be necessary to use tagged/vlan interface for the eap proxy. Specifying `eth1` should be sufficient.

Perhaps this is something goofy with the WRT3200ACM firmware?

**Comment by adagari** [comment]
> What is the reason for using `eth1.2`? Unless you have a weird networking setup, it shouldn't be necessary to use tagged/vlan interface for the eap proxy. Specifying `eth1` should be sufficient.

I couldn't find a guide for setting up the eap proxy on OpenWrt so I tried putting together information I found on forums/blogs. The setup has worked for a while but i'm unsure if it is correct. Anyway, eth1.2 is a dmz vlan, I have one other device in it. I can work on tinkering and getting the logs tomorrow.

**Comment by pyther** [comment]
Here is a guide a wrote a few weeks back, perhaps it might be useful.
https://pyther.net/2020/05/03/bypass-att-gateway-openwrt.html

I'd be curious to learn more about how you have things configured. I'm assuming eth1 is your WAN port on your router?

**Comment by adagari** [comment]
> Here is a guide a wrote a few weeks back, perhaps it might be useful.
> https://pyther.net/2020/05/03/bypass-att-gateway-openwrt.html
> 
> I'd be curious to learn more about how you have things configured. I'm assuming eth1 is your WAN port on your router?

Yes on the WRT3200ACM, eth1.2 is the default configuration for WAN. There is eth0.1 which has the LAN ports untagged. I setup a dmz at eth0.10 with two hosts, one being the ATT gateway. I'm going to take a look at the guide you wrote and see if I can adjust my configuration.

**Comment by pyther** [comment]
That make sense, sounds like you got it setup correctly. I've been so spoiled with x86_64 devices that I've kinda forgotten how all-in-one routers work.

I'm not really sure how to improve the logic in the init script. Perhaps we could trigger a reload when the two interfaces come up. Let me ponder this and review the openwrt procd documentation. May ask you you to do some testing if you are up for it.

Presumably, right now you need to wait at least 30 seconds after boot before you can get online. Since goeap_proxy fails, and then there is a the 30 second respawn logic. At which point, your authenticated and dhcp should work at that point.

**Comment by adagari** [comment]
I'm going to work on it tomorrow. If I find a solution I'll submit a pull request.

**Comment by adagari** [comment]
I spent yesterday testing and doing some dugging with procd. I tried setting up a procd_add_interface_trigger with wan, lol. I spent so long trying to figure out why it would not come up but I think it can't come up because the packets aren't being proxied yet. If I set it to the interface I use for wireguard it starts normally and doesn't throw an error, but this solution is not ideal. I thought about including a while loop in the start service method which would check for the directories "/sys/class/net/\<interface\>" and once they exist proceed with the startup sequence. Have you had any thoughts on how you would proceed? I can test my idea and submit a pull if you would like.

**Comment by pyther** [comment]
I've been pondering a bit, but haven't come up with any good solutions. I'm a little confused to your setup. If eth1.2 is how are you able to create a vlan0 interface ontop of that? Any chance you could share your /etc/config/network?

**Comment by pyther** [comment]
I was able to get `procd_add_interface_trigger` working in my testing. What I discovered is the openwrt interface name needs to be passed in, not the physical name (`eth1`). 

I made a few changes to the init script which should help out in your situation. Give it a try and let me know if it works. Make sure to update `/etc/config/goeap_proxy` as it now uses openwrt interface names instead of physical device names. https://github.com/pyther/openwrt-feed/pull/2

With this line, `ubus -t 30 wait_for "network.interface.${wan}" "network.interface.${router}"` goeap_proxy shouldn't start until the interface is up. However, if that isn't the case, the interface trigger should do the trick.

Here is snippet of my /etc/config/network
```
config interface 'wan'
	option proto 'dhcp'
	option ifname 'eth2.0'
	option macaddr '88:71:BB:AA:AA:AA'
	option peerdns '0'

config interface 'ont'
	option proto 'none'
	option ifname 'eth2'

config interface 'rgw'
	option proto 'none'
	option ifname 'eth3'
```

**Comment by adagari** [comment]
I replaced the init.d file and the config and now it is 100% working on startup. The log now only shows the negotiation. Thank you for your great work.

**Comment by pyther** [comment]
Fantastic! I've updated master to include these changes (https://github.com/pyther/openwrt-feed/commit/b3205370d6a2814591996166e6057b3492fd1717). Also, improved the error messages in goeap_proxy to hopefully make failures a little less cryptic. https://github.com/pyther/goeap_proxy/commit/5b0269c4d1ef52a5f479930c36f1ba2ea8bd9118

**Comment by adagari** [comment]
I went ahead and compiled a new package today. One thing I thought I would bring to your attention, 

> Fri May 29 17:38:44 2020 kern.info goeap_proxy[2207]: proxy started. router: eth0.10, wan: eth1.2
Fri May 29 17:38:52 2020 kern.info goeap_proxy[5102]: proxy started. router: eth0.10, wan: eth1.2
Fri May 29 17:39:01 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP v1, len 15, Request (1) id 1 > eth0.10
Fri May 29 17:39:01 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 22, Response (2) id 1 > eth1.2
Fri May 29 17:39:01 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > ff:ff:ff:ff:ff:ff, EAP v1, len 6, Request (1) id 2 > eth0.10
Fri May 29 17:39:02 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 92, Response (2) id 2 > eth1.2
Fri May 29 17:39:02 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > ff:ff:ff:ff:ff:ff, EAP v1, len 1020, Request (1) id 3 > eth0.10
Fri May 29 17:39:02 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 6, Response (2) id 3 > eth1.2
Fri May 29 17:39:02 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > ff:ff:ff:ff:ff:ff, EAP v1, len 1020, Request (1) id 4 > eth0.10
Fri May 29 17:39:02 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 6, Response (2) id 4 > eth1.2
Fri May 29 17:39:02 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > ff:ff:ff:ff:ff:ff, EAP v1, len 285, Request (1) id 5 > eth0.10
Fri May 29 17:39:02 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 906, Response (2) id 5 > eth1.2
Fri May 29 17:39:02 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > ff:ff:ff:ff:ff:ff, EAP v1, len 6, Request (1) id 6 > eth0.10
Fri May 29 17:39:03 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 902, Response (2) id 6 > eth1.2
Fri May 29 17:39:03 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > ff:ff:ff:ff:ff:ff, EAP v1, len 6, Request (1) id 7 > eth0.10
Fri May 29 17:39:03 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 902, Response (2) id 7 > eth1.2
Fri May 29 17:39:03 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > ff:ff:ff:ff:ff:ff, EAP v1, len 6, Request (1) id 8 > eth0.10
Fri May 29 17:39:03 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 484, Response (2) id 8 > eth1.2
Fri May 29 17:39:03 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > ff:ff:ff:ff:ff:ff, EAP v1, len 69, Request (1) id 9 > eth0.10
Fri May 29 17:39:04 2020 kern.info goeap_proxy[5102]: eth0.10: ff:ff:ff:ff:ff:ff > 01:80:c2:00:00:03, EAP v2, len 6, Response (2) id 9 > eth1.2
Fri May 29 17:39:04 2020 kern.info goeap_proxy[5102]: eth1.2: 00:90:d0:63:ff:01 > 01:80:c2:00:00:03, EAP v1, len 4, Success (3) id 9 > eth0.10
Fri May 29 17:39:07 2020 kern.info goeap_proxy[5782]: proxy started. router: eth0.10, wan: eth1.2

The new triggers spawn three processes. I went ahead and commented out line 41 and 42 and now there is only one process. Other than that, everything is working as expected.

**Comment by pyther** [comment]
There is code in goeap_proxy that prevents multiple instances from running at the same time. It seems like the interface trigger event is getting called three times. I'll see if I can add some code to log a shutdown event. That should at least make things a bit more obvious. I'm on the fence on what the right behavior is.

Do I remove the interface trigger? That would make the logs cleaner. In theory goeap_proxy can handle the interface going up/down once we are in the `proxyPackets()` loop, assuming the actual hardware doesn't change. 

On the flip side, restarting every time either interface comes up, ensures we are always in clean state. This seems like the safer approach give how critical this service is to getting online.

**Comment by adagari** [comment]
I don't think there is any right or wrong answer for this activity. The proxy does prevent itself from having multiple instances, but it is restarted three times, in my case, while booting. Personally, I removed the triggers as the init script already handles restarting if the process crashes. I thought I would note the activity for you in case you were interested.

**Comment by pyther** [comment]
Appreciate you letting me know about this. Thank you. I spent time yesterday thinking about various situations and edge case.

I've ended up removing the interface triggers. And added a reload trigger when the network config changes. Note, a reload will only take place if the goeap_proxy command changes. The repo has been updated so feel free to rebuild a new package.

**Documenting Assumptions/Notes**

I am assuming that network interfaces are not being added/removed from the system. This may be bad assumption for usb network devices, I'm not sure if the Interface object changes when a device is removed and then readded.

- The proxy calls `net.InterfaceByName` to get an Interface object. This interface object should not change when a device goes `up` or `down`. The proxy has error handling to handle errors returned when state changes. Therefore a service restart is not needed when the interface state changes. 
- If a device needs extra time to come up at boot `ubus -t 30 wait_for "network.interface.${wan}" "network.interface.${router}"` should be sufficient to allow the device to be created before the proxy is started.
- if network config is modified and the underlying device changes say `ONT` is changed from `eth3.100` to `eth3.200`. A restart will take place for goeap_proxy, but not enough time will pass for the device to be created. goeap_proxy will fail to get the device and exit. The respawn setting will respawn goeap_proxy after 30 seconds. Although this isn't ideal, this is probably a flow that is fairly infrequent and not worth addressing.

**Comment by adagari** [comment]
> 
> 
> Appreciate you letting me know about this. Thank you. I spent time yesterday thinking about various situations and edge case.
> 
> I've ended up removing the interface triggers. And added a reload trigger when the network config changes. Note, a reload will only take place if the goeap_proxy command changes. The repo has been updated so feel free to rebuild a new package.
> 
> **Documenting Assumptions/Notes**
> 
> I am assuming that network interfaces are not being added/removed from the system. This may be bad assumption for usb network devices, I'm not sure if the Interface object changes when a device is removed and then readded.
> 
>     * The proxy calls `net.InterfaceByName` to get an Interface object. This interface object should not change when a device goes `up` or `down`. The proxy has error handling to handle errors returned when state changes. Therefore a service restart is not needed when the interface state changes.
> 
>     * If a device needs extra time to come up at boot `ubus -t 30 wait_for "network.interface.${wan}" "network.interface.${router}"` should be sufficient to allow the device to be created before the proxy is started.
> 
>     * if network config is modified and the underlying device changes say `ONT` is changed from `eth3.100` to `eth3.200`. A restart will take place for goeap_proxy, but not enough time will pass for the device to be created. goeap_proxy will fail to get the device and exit. The respawn setting will respawn goeap_proxy after 30 seconds. Although this isn't ideal, this is probably a flow that is fairly infrequent and not worth addressing.

Updated to the latest package today, everything is working flawlessly.
